### ISSUE TITLE
Step 4: Core analysis

### ISSUE THREAD

**Issue by trannel** [ag-gipp/NLPLand#5]
These are the things we want to analyse using the expanded dataset. They might change over time.
We might generally want to look into things NLP scholar looked into for comparisions.
- [X] Most used words (see Step 2)
	- [X] By conference 
	- [x] By author (first author or in author list)
~~- [ ] By institution~~
	- [x] Over time (10 years, percentage based plot)
	- [X] Also check for bigrams
- [ ] Most studied topics (see Step 3)
	- [ ] By conference
	- [x] By author (first author or in author list)
	~~- [ ] By institution~~
	- [ ] Over time (10 years)
	- [ ] Measured by citations
- [ ] Amount of publications of top-k authors low-k authors and mid-k authors (idea 💡)
	- [ ] (first author/in author list) comparision
	- [ ] by conference (which authors are publishing were?)
- [X] Map different identifiers for conferences together
- [x] Compare our results with those of NLP Scholar
