### ISSUE TITLE
Step 5: Create the first embeddings

### ISSUE THREAD

**Issue by trannel** [ag-gipp/NLPLand#6]
Now that we have the dataset and already did some analysis on it, we now want to look into the semantic side. For this we first want to create some embeddings.
- [x] Decide on model for our first analysis
 	- fastText, (GloVe or word2vec)
- [x] Train the model
- [x] Decide how we want to save the embeddings (in the dataset)
- [ ] Create the embeddings for the papers (of one venue in one year, only using abstracts)
- [ ] Save the embeddings
